### ISSUE TITLE
bug: loading window is completely black

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#76]
<img width="376" alt="Screenshot 2024-07-02 at 23 42 04" src="https://github.com/Ramilito/kubectl.nvim/assets/59118341/7794fa8b-a09d-4f7a-8086-6a3948489d31">

**Comment by Ramilito** [comment]
Do you have any more info? Any errors?

**Comment by idelice** [comment]
No errors or anything. it doesn't matter what i do with the plugin, the loading bar is completely black like that

**Comment by idelice** [comment]
I can still do stuff. the loading bar is just black

**Comment by Ramilito** [comment]
Ah, the loading indicator is just supposed to be that spinner rotating 😅 , you can turn it back to the verbose printing if you want in the config, I thought maybe ppl would be annoyed by it:
```lua
{
  notification = {
    enabled = true,
    verbose = true <--- this line
  }
}
```

**Comment by idelice** [comment]
I'm actually more for the spinner part only, but the black bar is annoying. How can i make it transparent?

**Comment by Ramilito** [comment]
Ah, I get it now...it's transparent in my config by setting winblend in the buffer so not sure why it's black in yours, I'll take a look

**Comment by Ramilito** [comment]
I tried to understand the issue but I'm not sure why winblend isn't working in your config (I tried it my self), I also tried using fidget.nvim since that's a similar feature but it also has the same issue as my implementation.
The best compromise I could think of is to make the spinner take less space (1x1 square) and adding the option to disable winblend, so this should be working for you:
```lua
{
  notification = {
    enabled = true,
    verbose = false,
    blend = 0
  }
}
```
